<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/1_Basics/22_NumPy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# NumPy

## Notes

* NumPy, which stands for Numerical Python, is foundational for numerical computing in Python.
* Designed for scientific computation and is used extensively for data analysis because of its ability to handle large, multi-dimensional arrays and matrices efficiently.
* Serves as the basis for many other Python data science libraries, including Pandas, due to its speed and efficiency in numerical computations.
* A few special use cases for NumPy specifically for data analysis:
    * Array operations
    * Linear algebra
    * Statistical functions
    * Random number generation

## Importance

* Important for data analysis.
* Way to store data in a structured format, making it easier to organize, access, and manipulate data.
* Pandas library is built on top of NumPy.

For more information on NumPy check out the official documentation [here](https://numpy.org/doc/1.26/).

## Array Operations

### Notes
* Creation: **`import numpy as np; np.array([1, 2, 3])`**
* Basic Operations:  `+`, `-`, `/`, `*` performed element-wise
* Slicing: **`array[1:3]`**
* Boolean Indexing: **`array[array > 0]`**

### Examples

Let's start with creating a fictional array with the number of years of experience required for five different data science job listings.

### Create an Array

In [1]:
# Install package
!conda install numpy

/bin/bash: line 1: conda: command not found


In [2]:
# Import Package
import numpy as np

In [3]:
# Example: An array representing the number of years of experience required for three different data science job listings.
years_of_experience = np.array([1, 2, 3, 4, 5])

### Basic Operations

Applying mathematics operations to the entire array.

#### Addition
Adding 1 year to the experience requirements for each job listing.

In [4]:
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

#### Subtraction

Subtracting 1 year from the experience requirements for each job listing.

In [5]:
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

#### Division

Dividing the experience requirements by 2 (maybe for a junior role).

In [6]:
years_of_experience_half = years_of_experience / 2
years_of_experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

#### Multiplication

Doubling the experience requirements for each job listing.

In [7]:
years_of_experience_double = years_of_experience * 2
years_of_experience_double

array([ 2,  4,  6,  8, 10])

### Slicing

Get subset of information from the array. Let's get the experience requirements for the second and third job postings.

In [8]:
# Example: Selecting the experience requirement for the second and third job listings.
second_and_third_jobs_experience = years_of_experience[1:3]
second_and_third_jobs_experience

array([2, 3])

### Boolean Indexing

Get items from the array that meet a specific condition. For this get only the job postings that require more than 2 years of experience.

In [9]:
# Example: Selecting only those job listings that require more than 1 year of experience.
jobs_with_more_than_one_year_exp = years_of_experience[years_of_experience > 2]
jobs_with_more_than_one_year_exp

array([3, 4, 5])

## Math Operations

### Notes

* Aggregate functions:
    * `sum`: sum
    * `prod`: product
    * `cumsum`: cumulative sum
    * `cumprod`: cumulative product
* Mathematical operations (we won't be going into this during the course):
    * `sqrt`
    * `exp`
    * `log`
    * `sin`
    * `cos`

### Examples

First lets create a list with 10 yearly salaries for a Senior Data Analyst job. We're just using a combination of the `random` library to get random integers between 100000 and 150000. Then using a `for` loop to get 10 (random) values.

In [10]:
import random

salary = [random.randint(100000, 150000) for num in range(10)]

In [11]:
salary

[134163,
 133337,
 124471,
 136616,
 121033,
 138047,
 117044,
 113265,
 131009,
 123769]

Now we'll convert this list into a NumPy array.

In [12]:
salary_array = np.array(salary)
salary_array

array([134163, 133337, 124471, 136616, 121033, 138047, 117044, 113265,
       131009, 123769])

### Sum

Calculate the total sum of the elements in the `salary_array`.

In [13]:
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

np.int64(1272754)

### Prod

Calculate the product of the elements in the `salary_array`.

In [14]:
# This is a conceptual example since taking the product of a boolean series isn't common
product_salaries = np.prod(salary_array)
product_salaries

np.int64(1782282617733278304)

### Cumsum (Cumulative Sum)

Calculates the cumulative sum of elements of the `salary_array`. It calculates the cumulative sum at each index, meaning each element in the output array is the sum of all preceding elements including the current one from the original array.

For the `salary_array`:

* First element of cumsum is 110003 (just the first element)
* Second element is 110003 + 133394 = 243397
* Third element is 243397 + 148741 = 392138
* And so on...

In [15]:
cumulative_sum_salaries = np.cumsum(salary_array)
cumulative_sum_salaries

array([ 134163,  267500,  391971,  528587,  649620,  787667,  904711,
       1017976, 1148985, 1272754])

### Cumprod (Cumulative Product)

Calculates the cumulative product of elements of the `salary_array`. It calculates the cumulative product at each index, meaning each element in the output array is the product of all preceding elements including the current one from the original array.

For the `salary_array`:

* First element of cumprod is 110003
* Second element is 110003 * 133394
* Third element is (110003 * 133394) * 148741
* And so on...

In [16]:
# Cumulative product of 'job_no_degree_mention' column (conceptual example)
cumulative_prod_salaries = np.cumprod(salary_array)
cumulative_prod_salaries

array([              134163,          17888891931,     2226648267543501,
        9047874539370106760,   437187814599799240, -5280367119167203272,
        4424349758677574496,  -274089778203910816,  7582958796344903008,
        1782282617733278304])

**Note**: Due to the large numbers, the cumulative product values quickly escalate to the point where they exceed the numerical limit for typical data types in Python, leading to integer overflow. This is why some numbers appear as negative.

## Statistics Operations

### Notes

A lot of these you can also use Pandas because Pandas is built on top of NumPy. So here's a few examples but we won't be diving deep into them.

* `mean`
* `median`
* `var`: variance
* `std`: standard deviation
* `min`
* `max`

### Mean

Calculate the average salary in the `salary_array`.

In [18]:
average_salary = np.mean(salary_array)
average_salary

np.float64(127275.4)

### Median

Find the median salary in the `salary_array`.

In [19]:
median_salary = np.median(salary_array)
median_salary

np.float64(127740.0)

### Var

Calculate the variance of the `salary_array`.

In [20]:
salary_variance = np.var(salary_array, ddof=1)  # ddof=1 for sample variance
salary_variance

np.float64(73499542.71111111)

### Std

Calculate the standard deviation of the `salary_array`.

In [21]:
# Standard deviation of 'salary_year_avg' column
salary_std_dev = np.std(salary_array, ddof=1)  # ddof=1 for sample standard deviation
salary_std_dev

np.float64(8573.187430070051)

### Min

Find the minimum element in the `salary_array`.

In [22]:
# Minimum of 'salary_year_avg' column
min_salary = np.min(salary_array)
min_salary

np.int64(113265)

### Max

Find the maximum element in the `salary_array`.

In [23]:
# Maximum of 'salary_year_avg' column
max_salary = np.max(salary_array)
max_salary

np.int64(138047)

## NaN


### Notes

* Generate NaN values using `np.nan`
* `np.nan` value is used in NumPy (and by extension, Pandas) to represent missing or undefined data
* Helpful because it:
    * Handles missing data.
    * Helps with computations since it won't return errors but instead return `np.nan`.
    * Help filter out or fill in missing data using other methods that we'll use often in the `pandas` library like `dropna()`, `fillna()`, `isna()`, or `notna()`.

### Examples

Below are a few examples of what you can do.

#### Insert Missing Values

If you want to insert missing values into your array intentionally, perhaps to indicate that data is expected but not yet available. You use `np.nan`.

In [24]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

#### Replace Values with NaN

If you want to replace existing values with `np.nan`, for example, if certain values are considered invalid or outliers:

In [25]:
salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

## Where

### Notes

* `np.where` check elements of an array against a condition and to assign a value for True and another for false.
* Syntax: `np.where(condition)`.
* It's commonly used to conditionally replace array elements.

### Example

We're going to replace all values in `salary_array` that are less than 120,000 with 120,000 (to apply a minimum salary threshold). We'll use this syntax for it: `np.where(condition, x, y)`. With a `condition` and if it's true we do `x` and if not then do `y`.

In [26]:
# Replace values using np.where
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

array([134163, 133337, 124471, 136616, 121033, 138047, 120000, 120000,
       131009, 123769])

## Random Sampling

### Notes
* Generate a random numbers or samples.
* `np.random.normal` - draws random samples from a normal (Gaussian) distribution.
    * Specify the Arguments:
        * `loc`: This is the mean (`μ`) of the normal distribution.
        * `scale`: This is the standard deviation (`σ`) of the normal distribution, representing the dispersion from the mean.
        * `size`: This defines the number of random samples to draw, which is set to match the number of job postings.
    * Syntax: `np.random.normal(loc=0.0, scale=1.0, size=None)`
* A few other random sampling functions:
    * `np.random.rand`
    * `np.random.randn`
    * `np.random.randint`
    * `np.random.random`
    * `np.random.uniform`
    * `np.random.binomial`
    * `np.random.poisson`

### Example

Let's add some random noise to the `salary_array` to simulate salary variations. We can generate random values from a normal distribution with a mean of 0 and a standard deviation of 5000, then add these values to the salaries.

**Why?** This can be used to simulate salary data for job postings if actual salary data isn't available, for instance, in modeling or simulation scenarios.

In [ ]:
# Generate numbers based on normal distribution
noise = np.random.normal(0, 5000, salary_array.size)
# Add these numbers to the salary_array
salary_array_with_noise = salary_array + noise
salary_array_with_noise

array([124219.08195846, 131116.06759323, 119455.49265214, 122182.62053755,
       118818.2917239 , 151255.86681034, 130457.25819974, 143396.35776544,
       120961.92775885, 130976.31025803])

In [37]:
import random
marks = [random.randint(20,99) for range in range(75)]

student_marks  = np.array(marks)
print(student_marks)
print('\n')
print(f'Mean: {np.mean(student_marks)}')
print(f'Median: {np.median(student_marks)}')
print(f'Variance: {np.var(student_marks, ddof=1)}')
print(f'Standard Deviation: {np.std(student_marks, ddof=1)}')

for marks in student_marks:


[50 49 52 37 22 92 97 66 71 80 74 30 97 25 45 41 76 59 46 33 35 58 37 98
 60 49 99 68 79 62 67 38 51 20 96 28 31 22 52 90 32 20 48 52 27 91 27 90
 69 28 58 99 86 41 97 28 33 84 45 99 27 30 44 58 49 63 82 23 53 26 58 77
 73 49 86]


Mean: 56.45333333333333
Median: 52.0
Variance: 602.9268468468468
Standard Deviation: 24.554568757093797


In [40]:
sorted_marks = np.sort(student_marks)[::-1]
top_5_marks = sorted_marks[:5]
print(f'Top 5 Marks: {top_5_marks}')

Top 5 Marks: [99 99 99 98 97]


####NAN handling


In [49]:
import numpy as np

# Original array with NaN values
a = np.array([20, np.nan, 45, np.nan, 42, np.nan, 78, np.nan,
              89, np.nan, 71, 44, 11, 25, 66, np.nan, np.nan])

print("Original array:")
print(a)

print("\nNaN positions (True = NaN):")
print(np.isnan(a))

print("\nOnly NaN values:")
print(a[np.isnan(a)])

# Mean ignoring NaN
mean_val = np.nanmean(a)
print("\nMean without NaN:", mean_val)

# Replace NaN with mean
filled = np.nan_to_num(a, nan=mean_val)

print("\nArray after replacing NaN with mean:")
print(filled)


Original array:
[20. nan 45. nan 42. nan 78. nan 89. nan 71. 44. 11. 25. 66. nan nan]

NaN positions (True = NaN):
[False  True False  True False  True False  True False  True False False
 False False False  True  True]

Only NaN values:
[nan nan nan nan nan nan nan]

Mean without NaN: 49.1

Array after replacing NaN with mean:
[20.  49.1 45.  49.1 42.  49.1 78.  49.1 89.  49.1 71.  44.  11.  25.
 66.  49.1 49.1]


In [51]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Perform matrix multiplication using the @ operator (or np.dot())
C = A @ B

print("\nResult of A * B (matrix multiplication):")
print(C)

print("\n---\n")

print("NumPy's linear algebra functions are primarily found in the `numpy.linalg` module. Here are some of the key operations:")
print("\n1.  **Basic Operations:**")
print("    *   `np.dot(a, b)` or `a @ b`: Dot product of two arrays (matrix multiplication for 2D arrays).")
print("\n2.  **Decompositions:**")
print("    *   `np.linalg.eig(a)`: Compute the eigenvalues and right eigenvectors of a square array.")
print("    *   `np.linalg.eigh(a)`: Return the eigenvalues and eigenvectors of a complex Hermitian (symmetric if real) matrix.")
print("    *   `np.linalg.svd(a)`: Singular Value Decomposition.")
print("    *   `np.linalg.cholesky(a)`: Cholesky decomposition.")
print("    *   `np.linalg.qr(a)`: QR decomposition.")
print("\n3.  **Matrix and Vector Norms:**")
print("    *   `np.linalg.norm(a)`: Compute the Frobenius norm (or other norms) of a matrix or vector.")
print("\n4.  **Inverses and Determinants:**")
print("    *   `np.linalg.inv(a)`: Compute the (multiplicative) inverse of a matrix.")
print("    *   `np.linalg.pinv(a)`: Compute the (Moore-Penrose) pseudo-inverse of a matrix.")
print("    *   `np.linalg.det(a)`: Compute the determinant of an array.")
print("\n5.  **Solving Linear Equations:**")
print("    *   `np.linalg.solve(a, b)`: Solve a linear matrix equation, or system of linear scalar equations.")
print("    *   `np.linalg.lstsq(a, b)`: Return the least-squares solution to a linear matrix equation.")
print("\n6.  **Other Useful Functions:**")
print("    *   `np.linalg.matrix_rank(M)`: Return matrix rank of array using SVD method.")
print("    *   `np.trace(a)`: Return the sum along diagonals of the array.")


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of A * B (matrix multiplication):
[[19 22]
 [43 50]]

---

NumPy's linear algebra functions are primarily found in the `numpy.linalg` module. Here are some of the key operations:

1.  **Basic Operations:**
    *   `np.dot(a, b)` or `a @ b`: Dot product of two arrays (matrix multiplication for 2D arrays).

2.  **Decompositions:**
    *   `np.linalg.eig(a)`: Compute the eigenvalues and right eigenvectors of a square array.
    *   `np.linalg.eigh(a)`: Return the eigenvalues and eigenvectors of a complex Hermitian (symmetric if real) matrix.
    *   `np.linalg.svd(a)`: Singular Value Decomposition.
    *   `np.linalg.cholesky(a)`: Cholesky decomposition.
    *   `np.linalg.qr(a)`: QR decomposition.

3.  **Matrix and Vector Norms:**
    *   `np.linalg.norm(a)`: Compute the Frobenius norm (or other norms) of a matrix or vector.

4.  **Inverses and Determinants:**
    *   `np.linalg.inv(a)`: Compute the (multiplicative) inverse of a 